In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [3]:
df = pd.read_csv(r"C:\Users\hp\Documents\creditcard.csv")

In [3]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
df.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [5]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.168375e-15,3.416908e-16,-1.379537e-15,2.074095e-15,9.604066e-16,1.487313e-15,-5.556467e-16,1.213481e-16,-2.406331e-15,...,1.654067e-16,-3.568593e-16,2.578648e-16,4.473266e-15,5.340915e-16,1.683437e-15,-3.660091e-16,-1.227390e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [4]:
df["Class"].value_counts() # 0 for normal transaction and 1 for fraud transaction

Class
0    284315
1       492
Name: count, dtype: int64

In [8]:
fraud_data = df.loc[(df["Class"]==1)]
normal_data = df.loc[(df["Class"]==0)]

In [12]:
df.groupby("Class").mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [13]:
normal_sample = normal_data.sample(n=500) #creating a new dataset that contains some random samples from the noraml_data dataset

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
121178,76099.0,1.429589,-0.321934,-0.214901,-0.711276,-0.473371,-0.952159,-0.148052,-0.247587,-1.095188,...,0.205909,0.574029,-0.119057,0.105335,0.711202,-0.052441,-0.012501,-0.004555,1.00,0
132007,79818.0,-1.160389,0.512853,-0.200617,0.093043,2.342644,4.275577,1.277423,-0.045054,0.510139,...,-0.367796,-0.064421,-0.609551,1.053808,-0.070187,-0.436744,-1.022498,-1.044492,160.96,0
32056,36621.0,1.217866,0.477460,-0.000901,1.036925,0.024118,-0.977330,0.477952,-0.241165,-0.603876,...,0.072600,0.243767,-0.137563,0.565915,0.806446,-0.327767,-0.009473,0.003764,2.69,0
154549,101964.0,-1.077302,1.039880,1.717907,1.282414,-1.176868,1.277766,2.416680,-0.587623,1.286195,...,-0.823130,-1.267216,-0.044935,-0.080285,0.405122,-0.861616,0.161309,-0.223199,366.77,0
166154,117898.0,-0.226808,1.130806,0.611263,3.546429,-0.047816,0.387105,0.287615,0.541130,-0.900566,...,0.386310,1.195098,-0.041389,0.060479,-0.320319,0.259426,-0.021546,0.020627,50.47,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145372,86883.0,-0.313786,-0.073996,0.986873,-2.631431,0.559573,0.355142,0.184211,-0.063087,-0.488159,...,0.229269,0.889171,-0.407823,-0.338056,0.186973,-0.157988,0.192469,-0.030400,14.99,0
45352,42304.0,1.164032,0.932139,0.285149,3.687862,0.330714,-0.550697,0.593409,-0.207496,-1.591369,...,-0.015079,-0.153800,-0.093569,0.349123,0.686302,0.063553,-0.046149,0.014606,14.42,0
282303,170799.0,-0.338121,1.223452,-0.088550,-0.129047,-0.089467,-1.730682,0.763411,0.047190,-0.361722,...,0.490535,1.575801,0.034080,0.932049,-0.872699,-0.272577,0.394389,0.262405,5.99,0
164412,116700.0,2.045314,0.272344,-1.726128,0.549460,0.233129,-1.528117,0.339173,-0.441817,0.471909,...,0.202628,0.786312,-0.035054,-0.005403,0.275477,-0.107095,0.002730,-0.026134,9.20,0
22697,32387.0,0.828310,-0.639537,0.761657,0.730614,-1.104369,-0.611673,-0.139956,-0.104699,0.422803,...,0.073174,-0.232082,-0.103134,0.425044,0.076913,0.333658,-0.048037,0.061565,211.05,0

In [30]:
new_df = pd.concat([normal_sample,fraud_data]) # created new_df dataset that contains fraud and normal data in a balanced way
new_df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
121178,76099.0,1.429589,-0.321934,-0.214901,-0.711276,-0.473371,-0.952159,-0.148052,-0.247587,-1.095188,...,0.205909,0.574029,-0.119057,0.105335,0.711202,-0.052441,-0.012501,-0.004555,1.00,0
132007,79818.0,-1.160389,0.512853,-0.200617,0.093043,2.342644,4.275577,1.277423,-0.045054,0.510139,...,-0.367796,-0.064421,-0.609551,1.053808,-0.070187,-0.436744,-1.022498,-1.044492,160.96,0
32056,36621.0,1.217866,0.477460,-0.000901,1.036925,0.024118,-0.977330,0.477952,-0.241165,-0.603876,...,0.072600,0.243767,-0.137563,0.565915,0.806446,-0.327767,-0.009473,0.003764,2.69,0
154549,101964.0,-1.077302,1.039880,1.717907,1.282414,-1.176868,1.277766,2.416680,-0.587623,1.286195,...,-0.823130,-1.267216,-0.044935,-0.080285,0.405122,-0.861616,0.161309,-0.223199,366.77,0
166154,117898.0,-0.226808,1.130806,0.611263,3.546429,-0.047816,0.387105,0.287615,0.541130,-0.900566,...,0.386310,1.195098,-0.041389,0.060479,-0.320319,0.259426,-0.021546,0.020627,50.47,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [26]:
X = new_df.drop("Class",axis=1) #stored all new_df dataset in X except Class column's values
y = new_df["Class"] #stored Class column's values in y

In [36]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [37]:
var = LogisticRegression()

In [42]:
var.fit(X_train,y_train) #training our data

LogisticRegression()

In [53]:
print(len(var.predict(X_test)))

199

In [49]:
var.score(X_test,y_test) # Accuracy score of testing data

0.9396984924623115

In [50]:
var.score(X_train,y_train) #Accuracy score of training data

0.9432534678436317